// examples/solid/src/main.jsx
import { render } from "solid-js/web";
import App from "./App";

// Registers <clock-ui>. Solid compiles unknown tags to real DOM elements, so
// no configuration is needed.
import "@clock-ui/dom/element";
import "@clock-ui/dom/base.css";
import "./styles.css";

render(() => <App />, document.getElementById("root"));

// examples/react/src/main.tsx
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import App from "./App";

// The stylesheet is required — without it the clock renders at zero size.
import "@clock-ui/react/base.css";
import "./styles.css";

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <App />
  </StrictMode>,
);
